<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SugesoesSeeders2 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sugestaos')->insert([

            // Sugestões existentes...

            [
                'nome' => 'Tofu Grelhado com Legumes',
                'descricao' => 'Tofu grelhado com brócolis, pimentão e abobrinha.',
                'calorias' => 180,
                'proteinas' => 12.0,
                'carboidratos' => 14.0,
                'gorduras' => 8.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Frutas Vermelhas com Iogurte Grego',
                'descricao' => 'Iogurte grego com mix de frutas vermelhas.',
                'calorias' => 150,
                'proteinas' => 8.0,
                'carboidratos' => 20.0,
                'gorduras' => 4.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Bowl de Açaí com Granola e Frutas',
                'descricao' => 'Açaí batido com banana, granola e morangos.',
                'calorias' => 350,
                'proteinas' => 6.0,
                'carboidratos' => 72.0,
                'gorduras' => 5.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Wrap Integral de Atum e Abacate',
                'descricao' => 'Wrap integral recheado com atum, abacate e alface.',
                'calorias' => 260,
                'proteinas' => 18.0,
                'carboidratos' => 30.0,
                'gorduras' => 10.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Salada de Grão-de-Bico com Tomate e Pepino',
                'descricao' => 'Salada refrescante de grão-de-bico, tomate e pepino.',
                'calorias' => 200,
                'proteinas' => 10.0,
                'carboidratos' => 35.0,
                'gorduras' => 5.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Mingau de Aveia com Maçã e Canela',
                'descricao' => 'Aveia cozida com pedaços de maçã e toque de canela.',
                'calorias' => 220,
                'proteinas' => 6.0,
                'carboidratos' => 40.0,
                'gorduras' => 5.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Salada de Frutas Tropicais',
                'descricao' => 'Mix de frutas tropicais como manga, abacaxi e kiwi.',
                'calorias' => 150,
                'proteinas' => 2.0,
                'carboidratos' => 35.0,
                'gorduras' => 0.5,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Brócolis ao Vapor com Amêndoas',
                'descricao' => 'Brócolis cozido no vapor com amêndoas torradas.',
                'calorias' => 120,
                'proteinas' => 4.0,
                'carboidratos' => 8.0,
                'gorduras' => 8.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Lentilha com Espinafre e Alho',
                'descricao' => 'Lentilha cozida com espinafre e temperos naturais.',
                'calorias' => 180,
                'proteinas' => 12.0,
                'carboidratos' => 30.0,
                'gorduras' => 3.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Crepioca com Queijo Branco e Tomate',
                'descricao' => 'Crepioca recheada com queijo branco e tomate.',
                'calorias' => 250,
                'proteinas' => 12.0,
                'carboidratos' => 32.0,
                'gorduras' => 8.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Brownie de Batata Doce',
                'descricao' => 'Brownie saudável feito com batata doce e cacau.',
                'calorias' => 200,
                'proteinas' => 4.0,
                'carboidratos' => 30.0,
                'gorduras' => 8.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Panqueca de Banana com Aveia',
                'descricao' => 'Panqueca feita com banana e aveia, ideal para café da manhã.',
                'calorias' => 180,
                'proteinas' => 6.0,
                'carboidratos' => 35.0,
                'gorduras' => 4.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Salmão ao Forno com Aspargos',
                'descricao' => 'Filé de salmão assado com aspargos frescos.',
                'calorias' => 320,
                'proteinas' => 30.0,
                'carboidratos' => 5.0,
                'gorduras' => 20.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Mariscos',
            ],
            [
                'nome' => 'Torta de Abóbora e Espinafre',
                'descricao' => 'Torta leve de abóbora com espinafre e queijo branco.',
                'calorias' => 210,
                'proteinas' => 10.0,
                'carboidratos' => 20.0,
                'gorduras' => 10.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Smoothie de Frutas Vermelhas',
                'descricao' => 'Bebida refrescante feita com mix de frutas vermelhas.',
                'calorias' => 180,
                'proteinas' => 2.0,
                'carboidratos' => 40.0,
                'gorduras' => 1.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Omelete com Queijo e Espinafre',
                'descricao' => 'Omelete de ovos com queijo branco e espinafre.',
                'calorias' => 230,
                'proteinas' => 18.0,
                'carboidratos' => 3.0,
                'gorduras' => 15.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Salada de Macarrão Integral',
                'descricao' => 'Macarrão integral com legumes frescos e molho leve.',
                'calorias' => 280,
                'proteinas' => 10.0,
                'carboidratos' => 50.0,
                'gorduras' => 8.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Bolinho de Grão-de-Bico',
                'descricao' => 'Bolinho crocante de grão-de-bico com especiarias.',
                'calorias' => 150,
                'proteinas' => 6.0,
                'carboidratos' => 25.0,
                'gorduras' => 3.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Wrap de Frango com Alface e Cenoura',
                'descricao' => 'Wrap recheado com frango desfiado, alface e cenoura.',
                'calorias' => 220,
                'proteinas' => 15.0,
                'carboidratos' => 30.0,
                'gorduras' => 6.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Sopa de Lentilha',
                'descricao' => 'Sopa nutritiva de lentilha com legumes.',
                'calorias' => 190,
                'proteinas' => 10.0,
                'carboidratos' => 30.0,
                'gorduras' => 5.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Risoto de Quinoa com Cogumelos',
                'descricao' => 'Risoto feito com quinoa e cogumelos frescos.',
                'calorias' => 240,
                'proteinas' => 12.0,
                'carboidratos' => 30.0,
                'gorduras' => 10.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Bowl de Frutas com Chia',
                'descricao' => 'Bowl com mix de frutas frescas e chia.',
                'calorias' => 160,
                'proteinas' => 2.0,
                'carboidratos' => 35.0,
                'gorduras' => 2.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Lasanha de Berinjela',
                'descricao' => 'Lasanha leve feita com berinjela e queijo magro.',
                'calorias' => 280,
                'proteinas' => 15.0,
                'carboidratos' => 20.0,
                'gorduras' => 12.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Bruschetta Integral com Tomate e Manjericão',
                'descricao' => 'Pão integral tostado com tomate e manjericão.',
                'calorias' => 130,
                'proteinas' => 4.0,
                'carboidratos' => 20.0,
                'gorduras' => 5.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Almôndegas de Carne com Arroz Integral',
                'descricao' => 'Almôndegas caseiras servidas com arroz integral.',
                'calorias' => 350,
                'proteinas' => 20.0,
                'carboidratos' => 45.0,
                'gorduras' => 10.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Sanduíche Natural de Atum',
                'descricao' => 'Sanduíche feito com atum, alface e pão integral.',
                'calorias' => 210,
                'proteinas' => 14.0,
                'carboidratos' => 25.0,
                'gorduras' => 7.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Chips de Batata Doce',
                'descricao' => 'Batata doce cortada em fatias finas e assada.',
                'calorias' => 150,
                'proteinas' => 2.0,
                'carboidratos' => 35.0,
                'gorduras' => 0.5,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Pizza de Abobrinha com Queijo',
                'descricao' => 'Pizza leve com base de abobrinha e queijo magro.',
                'calorias' => 200,
                'proteinas' => 8.0,
                'carboidratos' => 15.0,
                'gorduras' => 10.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Iogurte de Coco com Granola',
                'descricao' => 'Iogurte vegano de coco com granola crocante.',
                'calorias' => 180,
                'proteinas' => 3.0,
                'carboidratos' => 20.0,
                'gorduras' => 8.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Pão de Queijo Fit',
                'descricao' => 'Pão de queijo saudável com polvilho e queijo magro.',
                'calorias' => 100,
                'proteinas' => 3.0,
                'carboidratos' => 15.0,
                'gorduras' => 4.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Purê de Abóbora com Ervas',
                'descricao' => 'Purê cremoso de abóbora com toque de ervas.',
                'calorias' => 120,
                'proteinas' => 2.0,
                'carboidratos' => 25.0,
                'gorduras' => 2.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Mix de Nuts e Frutas Secas',
                'descricao' => 'Mix saudável de castanhas e frutas secas.',
                'calorias' => 200,
                'proteinas' => 5.0,
                'carboidratos' => 20.0,
                'gorduras' => 12.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Brócolis com Alho Assado',
                'descricao' => 'Brócolis assado com alho e azeite de oliva.',
                'calorias' => 100,
                'proteinas' => 4.0,
                'carboidratos' => 8.0,
                'gorduras' => 5.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Quibe de Abóbora com Linhaça',
                'descricao' => 'Quibe vegano de abóbora com linhaça.',
                'calorias' => 150,
                'proteinas' => 5.0,
                'carboidratos' => 25.0,
                'gorduras' => 3.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Bolinho de Espinafre e Ricota',
                'descricao' => 'Bolinho leve de espinafre com ricota.',
                'calorias' => 90,
                'proteinas' => 6.0,
                'carboidratos' => 7.0,
                'gorduras' => 4.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Bolo de Cenoura Integral',
                'descricao' => 'Bolo de cenoura com farinha integral e açúcar mascavo.',
                'calorias' => 150,
                'proteinas' => 3.0,
                'carboidratos' => 25.0,
                'gorduras' => 6.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Tabule de Quinoa com Tomate',
                'descricao' => 'Tabule feito com quinoa, tomate e pepino.',
                'calorias' => 180,
                'proteinas' => 6.0,
                'carboidratos' => 30.0,
                'gorduras' => 4.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Torta de Batata Doce com Frango',
                'descricao' => 'Torta feita com purê de batata doce e frango desfiado.',
                'calorias' => 250,
                'proteinas' => 15.0,
                'carboidratos' => 35.0,
                'gorduras' => 8.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Salada Grega com Queijo Feta',
                'descricao' => 'Salada fresca com tomate, pepino, azeitonas e queijo feta.',
                'calorias' => 180,
                'proteinas' => 6.0,
                'carboidratos' => 12.0,
                'gorduras' => 12.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Frango ao Curry com Arroz Integral',
                'descricao' => 'Frango cozido ao curry com arroz integral.',
                'calorias' => 320,
                'proteinas' => 20.0,
                'carboidratos' => 40.0,
                'gorduras' => 8.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Biscoito de Aveia com Mel',
                'descricao' => 'Biscoito crocante de aveia com mel.',
                'calorias' => 100,
                'proteinas' => 2.0,
                'carboidratos' => 18.0,
                'gorduras' => 3.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Sorvete de Banana e Cacau',
                'descricao' => 'Sorvete natural feito com banana congelada e cacau em pó.',
                'calorias' => 120,
                'proteinas' => 2.0,
                'carboidratos' => 30.0,
                'gorduras' => 1.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Abacaxi Grelhado com Canela',
                'descricao' => 'Fatias de abacaxi grelhadas e polvilhadas com canela.',
                'calorias' => 80,
                'proteinas' => 1.0,
                'carboidratos' => 20.0,
                'gorduras' => 0.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Brownie de Cacau e Castanhas',
                'descricao' => 'Brownie saudável feito com cacau e castanhas.',
                'calorias' => 200,
                'proteinas' => 4.0,
                'carboidratos' => 20.0,
                'gorduras' => 10.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Macarrão de Abobrinha com Pesto',
                'descricao' => 'Macarrão de abobrinha com molho pesto.',
                'calorias' => 120,
                'proteinas' => 2.0,
                'carboidratos' => 10.0,
                'gorduras' => 8.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Veganos',
            ],
            [
                'nome' => 'Panqueca de Espinafre com Queijo Branco',
                'descricao' => 'Panqueca verde de espinafre com recheio de queijo branco.',
                'calorias' => 150,
                'proteinas' => 8.0,
                'carboidratos' => 15.0,
                'gorduras' => 6.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Crepioca de Frango com Requeijão',
                'descricao' => 'Crepioca recheada com frango desfiado e requeijão.',
                'calorias' => 200,
                'proteinas' => 15.0,
                'carboidratos' => 20.0,
                'gorduras' => 7.0,
                'categoria' => '+calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Chá Gelado de Hibisco com Limão',
                'descricao' => 'Chá de hibisco com limão, refrescante e sem calorias.',
                'calorias' => 10,
                'proteinas' => 0.0,
                'carboidratos' => 2.0,
                'gorduras' => 0.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Salada de Rúcula com Manga',
                'descricao' => 'Salada de rúcula fresca com pedaços de manga madura.',
                'calorias' => 120,
                'proteinas' => 2.0,
                'carboidratos' => 18.0,
                'gorduras' => 5.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Nenhuma',
            ],
            [
                'nome' => 'Iogurte Grego com Mel e Amêndoas',
                'descricao' => 'Iogurte grego natural com mel e amêndoas tostadas.',
                'calorias' => 180,
                'proteinas' => 8.0,
                'carboidratos' => 20.0,
                'gorduras' => 8.0,
                'categoria' => '+/-calorias',
                'restricoes_para' => 'Intolerância à lactose',
            ],
            [
                'nome' => 'Espetinho de Camarão com Legumes',
                'descricao' => 'Espetinhos de camarão grelhado com legumes variados.',
                'calorias' => 140,
                'proteinas' => 12.0,
                'carboidratos' => 8.0,
                'gorduras' => 4.0,
                'categoria' => '-calorias',
                'restricoes_para' => 'Mariscos',
            ],
            
            

        ]);
    }
}
